# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=false
# Fabric Properties
	# check these on https://fabricmc.net/use
minecraft_version=26.1-pre-2
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_version=0.143.14+26.1


# Mod Properties
	mod_version = 3.10.2+1.21.11
	maven_group = eu.pb4
	archives_base_name = graves

# Dependencies
